### ISSUE TITLE
Error occurred when executing VHS_LoadImages

### ISSUE THREAD

**Issue by jimmiles** [Kosinkadink/ComfyUI-VideoHelperSuite#10]
Try as I might, I can't do step one, loading images. I get a red error box:
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 437, in load_images
    raise FileNotFoundError(f"No files in directory '{directory}'.")
FileNotFoundError: No files in directory 'C:\ComfyUI_windows_portable\ComfyUI\input\Creeper'.

**Comment by jimmiles** [comment]
I might have fixed it. I converted the files in the folder to JPG. I didn't realize that was required!

**Comment by bihailantian655** [comment]
![屏幕截图 2023-11-05 120704](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/35267721/9e80812c-00c6-481a-858d-2123ccd7d7bb)
