### ISSUE TITLE
VideoCombine empty array

### ISSUE THREAD

**Issue by sendn0des** [Kosinkadink/ComfyUI-VideoHelperSuite#110]
array coming up empty on Videocombine (coming out of VFI). All nodes deleted and recreated.  updated to latest version and reboot.

COMFY ERROR:
Error occurred when executing VHS_VideoCombine:

index 0 is out of bounds for dimension 0 with size 0

  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 172, in combine_video
    Image.fromarray(tensor_to_bytes(images[0])).save(
    
    
    
    TERMINAL:
    Loading 1 new model
Comfy-VFI: Final clearing cache...
Comfy-VFI: Done cache clearing
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/whobody/Desktop/d_driveAI/AI/ComfyUI-master/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 172, in combine_video
    Image.fromarray(tensor_to_bytes(images[0])).save(
IndexError: index 0 is out of bounds for dimension 0 with size 0

Prompt executed in 18.21 seconds

**Comment by AustinMroz** [comment]
There is no processing that is done on the `images` input before this error occurs. It appears there's just 0 images being passed. Can you try outputting to a "Preview Image" and verify if you get any output?

**Comment by sendn0des** [comment]
Good call. It was split image batch. I had to reload that node too. A few of these had to be deleted, didnt go back far enough in flow!
