### ISSUE TITLE
A weird error after reading a json

### ISSUE THREAD

**Issue by YacratesWyh** [Kosinkadink/ComfyUI-VideoHelperSuite#117]
It was fine when I make it up. But when I open it afterwards it reports:
TypeError: Cannot read properties of undefined (reading 'custom_width')
    at ComfyNode.<anonymous> (http://localhost:8080/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:919:79)
    at object.<computed> (http://localhost:8080/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:16:22)
    at object.<computed> (http://localhost:8080/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:15:37)
    at object.<computed> (http://localhost:8080/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:15:37)
    at object.<computed> (http://localhost:8080/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:15:37)
    at object.<computed> [as onNodeCreated] (http://localhost:8080/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:15:37)
    at Object.createNode (http://localhost:8080/lib/litegraph.core.js:478:22)
    at LGraph.configure (http://localhost:8080/lib/litegraph.core.js:2215:38)
    at LGraph.configure (http://localhost:8080/scripts/app.js:1249:22)
    at LGraph.configure (http://localhost:8080/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)

Wonder why

**Comment by YacratesWyh** [comment]
Updated nodes, prblem fixed
