### ISSUE TITLE
When loading the graph, the following node types were not found: VHS_VideoCombine

### ISSUE THREAD

**Issue by qawsqwe** [Kosinkadink/ComfyUI-VideoHelperSuite#142]
When launching comfyui portable on windows 10 with everything up to date:

C:\Users\보물1호\Desktop\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2024-01-24 21:46:32.240884
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\보물1호\Desktop\ComfyUI\python_embeded\python.exe
** Log path: C:\Users\보물1호\Desktop\ComfyUI\comfyui.log
[ComfyUI-Manager] Windows event loop policy mode enabled

Prestartup times for custom nodes:
   0.1 seconds: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32660 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1929 [b9911dcb] | Released on '2024-01-23'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 15, in <module>
    from .load_video_nodes import LoadVideoUpload, LoadVideoPath
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2'
Total VRAM 8192 MB, total RAM 32660 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'cv2'
Traceback (most recent call last):
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds (IMPORT FAILED): C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   0.0 seconds (IMPORT FAILED): C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

![123456](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/157601724/68ec1003-cebf-4fcc-b9e5-543c09bf471f)

The solution I've tried is 
1. Go to the ComfyUI main folder
2. open the requirements.txt file and add
  opencv-python
  imageio-ffmpeg
3. Save requirements.txt
4. Click on update_comfyui_and_python_dependencies.bat

But this didn't solve it either.

Please help me

**Comment by shirubei** [comment]
Had the same error and solved according to #84 ( run commands list below)

python_embeded\python.exe -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless

python_embeded\python.exe -m pip install opencv-python==4.7.0.72

**Comment by Xorba001** [comment]
I ran into the same problem and got it fixed.
I was seeing numba in WASNode and got to try to resolve this. I found in the WASNode an install.bat file for their module.

What it did, ran the thing, it installed python_embedded stuff.

I restarted the ComfyUI, and the CV2 error was gone !

Had previously installed opencv, ffmpeg, imageio_ffmpeg to no avail. 
after running the install for WAS, VHS_ error red warning was gone and workspace loads just fine.

Hope this helps... somehow !
It's a work around but looking at the WASNode way that it embedded python might shed a light on the issue.

**Comment by Berkay-Akar** [comment]
> When launching comfyui portable on windows 10 with everything up to date:
> 
> C:\Users\보물1호\Desktop\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build ** ComfyUI startup time: 2024-01-24 21:46:32.240884 ** Platform: Windows ** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct 2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] ** Python executable: C:\Users\보물1호\Desktop\ComfyUI\python_embeded\python.exe ** Log path: C:\Users\보물1호\Desktop\ComfyUI\comfyui.log [ComfyUI-Manager] Windows event loop policy mode enabled
> 
> Prestartup times for custom nodes: 0.1 seconds: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 8192 MB, total RAM 32660 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync VAE dtype: torch.bfloat16 Using pytorch cross attention
> 
> ### Loading: ComfyUI-Manager (V2.2.5)
> ### ComfyUI Revision: 1929 [b9911dcb] | Released on '2024-01-23'
> FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json Traceback (most recent call last): File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite__init__.py", line 1, in from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 15, in from .load_video_nodes import LoadVideoUpload, LoadVideoPath File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> Cannot import C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2' Total VRAM 8192 MB, total RAM 32660 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync VAE dtype: torch.bfloat16 Traceback (most recent call last): File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\facerestore_cf__init__.py", line 6, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> Cannot import C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'cv2' Traceback (most recent call last): File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\nodes.py", line 1872, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui__init__.py", line 1, in from .WAS_Node_Suite import NODE_CLASS_MAPPINGS File "C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in from numba import jit ModuleNotFoundError: No module named 'numba'
> 
> Cannot import C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'
> 
> Import times for custom nodes: 0.0 seconds (IMPORT FAILED): C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\facerestore_cf 0.0 seconds: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation 0.0 seconds (IMPORT FAILED): C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui 0.0 seconds (IMPORT FAILED): C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite 0.4 seconds: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188 [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json FETCH DATA from: C:\Users\보물1호\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
> 
> ![123456](https://private-user-images.githubusercontent.com/157601724/299318105-68ec1003-cebf-4fcc-b9e5-543c09bf471f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzMzNzcsIm5iZiI6MTcyMzUzMzA3NywicGF0aCI6Ii8xNTc2MDE3MjQvMjk5MzE4MTA1LTY4ZWMxMDAzLWNlYmYtNGZjYy1iOWU1LTU0M2MwOWJmNDcxZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNzExMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzBmNGVmZmViZjE3OTAyZTgzNzk1MmYyY2UxY2Y0NzRmODZiMzVlYWIwOGUzMDZmZDU5OWEwMTVjOGRhMzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-tvpVXA79h0upsgYSEVqvsLq0l2XqI8eOucpQdpxRM)
> 
> The solution I've tried is
> 
> 1. Go to the ComfyUI main folder
> 2. open the requirements.txt file and add
>    opencv-python
>    imageio-ffmpeg
> 3. Save requirements.txt
> 4. Click on update_comfyui_and_python_dependencies.bat
> 
> But this didn't solve it either.
> 
> Please help me

I update my requirements.txt and worked for me
