### ISSUE TITLE
The only thing that comes to mind is that the system version of ffmpeg is installed is significantly old. Currently, the code will always prefer the system version of ffmpeg if it is available.

### ISSUE THREAD

**Issue by paukdesidn** [Kosinkadink/ComfyUI-VideoHelperSuite#149]
The only thing that comes to mind is that the system version of ffmpeg is installed is significantly old. Currently, the code will always prefer the system version of ffmpeg if it is available.

Does the problem persist if you force usage of the bundled imageio-ffmpeg python by either
- Uninstalling the system version of ffmpeg or
- Editing line 27 of videohelpersuite/nodes.py from `if ffmpeg_path is None` to `if True`

_Originally posted by @AustinMroz in https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/80#issuecomment-1840972054_
            
Hi I have follow you tip to change the line cone in the phyton file and now the node VHS_Video Combine is red.
![Screenshot 2024-02-05 184238](https://user-images.githubusercontent.com/66793428/302383975-841b1210-f110-4b55-b92b-d15d76cf252b.png)
I run ComfyUI on Window 11 pro, have gpu 4090. 
How I can fix it.

Thanks in advance!

**Comment by AustinMroz** [comment]
Thats an older post and the information in it is now out of date. I have since implemented a system that will test all found versions of ffmpeg and automatically pick the best. This should mean that that issue, as originally described, is no longer possible. I was hoping to get confirmation from the original author, but I should have closed that issue.

The node being highlighted in red means that the plugin failed to load. If you check the console window for comfyui, there should be an error message towards the top that describes what went wrong.

I recommend you revert your attempted change (or just reinstall the plugin if that's difficult) and send the error message you initially got.

**Comment by paukdesidn** [comment]
Ok, I have rewrite the line code as it was before and save file, after that nothing change. Did you mean I should reinstall ComfyUI or there is some method to fix this?
 In console now I have this issue:

Cannot import M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
Traceback (most recent call last):
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 286
    if ffmpeg_path if True:
                          ^
SyntaxError: invalid syntax

Cannot import M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: invalid syntax (nodes.py, line 286)
[comfyui_controlnet_aux] | INFO -> Using ckpts path: M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

After I press queue prompt I have this: 
FETCH DATA from: M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
Error handling request
Traceback (most recent call last):
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 620, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'
got prompt
Error handling request
Traceback (most recent call last):
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 620, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'

**Comment by paukdesidn** [comment]
![Screenshot 2024-02-06 000121](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/66793428/9d5d2edc-af23-46d0-aced-f59f14d4d4c5)
Here I add a screenshot to show where I changed the line code and after having red not in Comfyui I have changed back the line code. Thank you for your repostpones.
I'm definitely new user of Comfyui and this is my firs time that I opened phyton file, so completely don't know what should I do.

**Comment by AustinMroz** [comment]
I'm glad to help and I'm sorry you've gotten tied up on advice that was targeted at a more experienced user.

I meant that you could uninstall and reinstall ComfyUI-VideoHelperSuite using the manger button on the right. The current error you are getting is that there's still some changed code on line 284. Reinstalling VideoHelperSuite should fix that.

After that is fixed, there will likely be a new error message in the console I can help you with

**Comment by paukdesidn** [comment]
Thank you a lot I really appreciate you response. 
I did as you recommended, and now I have this error: 

Error occurred when executing VHS_VideoCombine:

An error occured in the ffmpeg subprocess:
Unknown encoder 'libsvtav1'


File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 348, in combine_video
output_process.send(images.tobytes())
File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 143, in ffmpeg_process
raise Exception("An error occured in the ffmpeg subprocess:\n" \


![Screenshot 2024-02-06 181635](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/66793428/e4988837-d7e0-4611-b8c4-c6804393329f)

**Comment by paukdesidn** [comment]
And this is msg from command panel:

Prompt executed in 125.40 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (60) greater than context_length 16.
[AnimateDiffEvo] - INFO - Using motion module mm_sd_v14.ckpt:v1.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:58<00:00,  5.91s/it]
Requested to load AutoencoderKL
Loading 1 new model
Unknown encoder 'libsvtav1'
[VideoHelperSuite] - WARNING - An error occurred when saving with metadata
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 136, in ffmpeg_process
    proc.stdin.write(frame_data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 348, in combine_video
    output_process.send(images.tobytes())
  File "M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 143, in ffmpeg_process
    raise Exception("An error occured in the ffmpeg subprocess:\n" \
Exception: An error occured in the ffmpeg subprocess:
Unknown encoder 'libsvtav1'

But with Gif format its works excellent, but with video formats have an issue. Thank you again!

**Comment by AustinMroz** [comment]
Do any of the other video formats (like h264) give errors?

The version of ffmpeg we bundle uses an older stable version of ffmpeg that lacks some advanced options (high performance av1 encoding and nvenc,  iirc). The solution to this is to install download a [newer version of ffmpeg](https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z) and adding it to the system path.

**Comment by paukdesidn** [comment]
With h264 also excellent result. Thank you a lot, I downloaded the zip folder.
Here is a msg from command path:

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: M:\StableDiffusion\ComfyUI\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['alphas_cumprod', 'alphas_cumprod_prev', 'betas', 'log_one_minus_alphas_cumprod', 'model_ema.decay', 'model_ema.num_updates', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'posterior_variance', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
[AnimateDiffEvo] - INFO - Loading motion module mm_sd_v14.ckpt via Gen2
[AnimateDiffEvo] - INFO - [Autoselect]: 'sqrt_linear (AnimateDiff)' beta_schedule for mm_sd_v14.ckpt:v1:AnimateDiff:SD1.5
Requested to load SD1ClipModel
Loading 1 new model
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (60) greater than context_length 16.
[AnimateDiffEvo] - INFO - Using motion module mm_sd_v14.ckpt:v1.
Requested to load BaseModel
Requested to load AnimateDiffModel
Loading 2 new models
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:52<00:00,  2.65s/it]
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Leftover VAE keys ['model_ema.decay', 'model_ema.num_updates']
Requested to load AutoencoderKL
Loading 1 new model
Prompt executed in 63.77 seconds

![Screenshot 2024-02-06 195208](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/66793428/482c47da-3d55-41b8-bba5-dc145058b374)

Thank you again!
