### ISSUE TITLE
Help!!!!That's been bothering me for a long time

### ISSUE THREAD

**Issue by VHS-1** [Kosinkadink/ComfyUI-VideoHelperSuite#171]
Error occurred when executing VHS_LoadVideoPath:

"E:\ComfyUI\comfyuiCHANCHU\chuli\wush.mp4" could not be loaded with cv.

File "E:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj. FUNCTION, allow_interrupt=True)
File "E:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
results. append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 228, in load_video
return load_video_cv(**kwargs)
File "E:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 120, in load_video_cv
(width, height, target_frame_time) = next(gen)
File "E:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 51, in cv_frame_generator
raise ValueError(f"{video} could not be loaded with cv.")

**Comment by AustinMroz** [comment]
A couple quick checks for clarity:
- Are you able to view this wush.mp4 outside of ComfyUI?
- Is it only some video files that you're unable to load?
- Does it still fail if you instead use forward slashes in your path? i.e. `E:/ComfyUI/comfyuiCHANCHU/chuli/wush.mp4`
- Is there any other error information given in the ComfyUI terminal window?

The legnth of code here where a bug could exist seems particularly narrow. The path suceeds validation checks, but fails immediately afterwards when passed to opencv.

**Comment by VHS-1** [comment]
Prompt executed in 0.01 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "J:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "J:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "J:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "J:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 228, in load_video
    return load_video_cv(**kwargs)
  File "J:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 120, in load_video_cv
    (width, height, target_frame_time) = next(gen)
  File "J:\ComfyUI\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 51, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: "J:/A01douy/cs/w2.mp4" could not be loaded with cv.

Prompt executed in 0.01 seconds

**Comment by VHS-1** [comment]
It's an error message for the root directory,
1. I have replaced a video file, which can be played in other places.
2. Fetching the video is the first step in this workflow, and it breaks before it runs
3. I also use backslashes

**Comment by AustinMroz** [comment]
I appreciate the quick response. From the information given, I suspect the issue lies with opencv itself.

There's probably not much that can be done to fix this, but there is a [load_video_alpha](/Kosinkadink/ComfyUI-VideoHelperSuite/tree/load_video_alpha) branch which instead loads videos with ffmpeg and may provide better results.

**Comment by Kosinkadink** [comment]
Hey, would be be able to upload the video file somewhere (or another video file that causes the same issue)? If there's some edge case in the code that's unaccounted for/a bug in opencv, having the file that can reproduce it would be a great help.

**Comment by VHS-1** [comment]
Ok, thank you for your inspiration. I will upload it in another way instead of using this node

**Comment by Kosinkadink** [comment]
I meant if you could upload the video for us to access so we can check out the issue ourselves - without being able to reproduce the issue, it's difficult to debug it.

**Comment by VHS-1** [comment]
Ok, I will study my project first, and later I will summarize the problems encountered and send them to youtube and then @ you

**Comment by Kosinkadink** [comment]
Summary is not needed, I'm saying we need the RAW video file that throws the errors. We are unable to reproduce the issue on our end, AKA we can't get the error to happen. It seems to be something about the specific video file you are trying to load. We need access to the video file that causes the error. It doesn't matter if you make a YouTube video talking about it, give a TED talk, or speak at the United Nations lol, I'm asking if you can provide a video file that you're trying too load for AustinMroz and I to try out locally. Otherwise, all he and I can do is speculate.
