### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by jkla139** [Kosinkadink/ComfyUI-VideoHelperSuite#174]
Traceback (most recent call last):
  File "C:\Downloads\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Downloads\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Downloads\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Downloads\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 183, in load_video
    return load_video_cv(**kwargs)
  File "C:\Downloads\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 131, in load_video_cv
    images = torch.from_numpy(np.fromiter(gen, np.dtype((np.float32, (height, width, 3)))))
ValueError: setting an array element with a sequence.

On "Load Video (upload)" node

**Comment by jkla139** [comment]
It's numpy version problem.
