### ISSUE TITLE
ERRNO 22 INVALID ARGUEMENT

### ISSUE THREAD

**Issue by Rpk247** [Kosinkadink/ComfyUI-VideoHelperSuite#190]
**Please help me.....!
I already done a fixing methods:
The nodes are working properly and today it rises the issue
1)Instruction.txt METHOD
2)if ffmpeg true in VHS/nodes.py METHOD
These are not working FOR ME**

ISSUE:
[Error occurred when executing VHS_VideoCombine:
[Errno 22] Invalid argument]

File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 364, in combine_video
output_process.send(image.tobytes())
File "D:\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 118, in ffmpeg_process
proc.stdin.write(frame_data)

**Comment by AustinMroz** [comment]
I believe I have a reproduction for this and am looking into it. On Windows, I get the same error in saving to files or folders which start with the letter t  or T even though logging is showing these paths to be properly escaped.

**Comment by AustinMroz** [comment]
I've found and pushed a fix for the issue I was able to reproduce. Let me know if this fixes it for you.

**Comment by jags111** [comment]
I am having the same issue after the updates
2024-04-11 22:05:09,677- root:180- ERROR- Traceback (most recent call last):
  File "D:\AI\comfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\comfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 364, in combine_video
    output_process.send(image.tobytes())
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 118, in ffmpeg_process
    proc.stdin.write(frame_data)
OSError: [Errno 22] Invalid argument

**Comment by Rpk247** [comment]
Still got an same error..
Please elaborate the steps i need to do. I'm a beginner for this.

**Comment by AustinMroz** [comment]
Unfortunately, I'm not sure. I can provide more insight on what I know, but I don't have any current guess for what the actual issue could be and the issue I was able to solve seems entirely unrelated to the issue both of you are facing.

The line that throws the error is misleading. The actual error occurs on line 114 because of something unknown that is wrong with the value of `m_args + [filepath]`. Contrary to my initial prediction, the escaping performed seems to be robust so the issue is most likely to lie in one of the three paths contained in the command.

Could you check if:
- You're able to save output in the 'image/gif' format?
- You still see the issue when `save_metadata` is unchecked?
- You still see the issue if you toggle `save_output`?

**Comment by Rpk247** [comment]
Yes, i can save image/gif formats
No save metadata & save output issues

**Comment by diipfeiks** [comment]
Maybe I can add some light to the problem (which I also have):
I also get an error 22 but I have more information. This is my report:
!!! Exception during processing !!! [Errno 22] Invalid argument: 'D:\\ComfyUI\\output\\2025-05-13T01:00:05_00001.png'

There is no such file in the comfyui\output folder (2025-05-13T01:00:05_00001.png)

The rest of the report:
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 347, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 222, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI\execution.py", line 194, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 183, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 382, in combine_video
    Image.fromarray(tensor_to_bytes(first_image)).save(
  File "D:\ComfyUI\venv\lib\site-packages\PIL\Image.py", line 2563, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'D:\\ComfyUI\\output\\2025-05-13T01:00:05_00001.png'
