### ISSUE TITLE
Update ComfyUI Node and getting error VHS_LoadVideo int is_integer

### ISSUE THREAD

**Issue by Darienxccs** [Kosinkadink/ComfyUI-VideoHelperSuite#265]
I updated my ComfyUI and now I try to use Liveportrait in V2V and I received this error message:

Error occurred when executing VHS_LoadVideo:

'int' object has no attribute 'is_integer'

i tried everything, reinstall, make new node, get the same error over and over

**Comment by stephennilor** [comment]
```
!!! Exception during processing !!! 'int' object has no attribute 'is_integer'
Traceback (most recent call last):
  File "D:\comfy-guill\ComfyUI\execution.py", line 314, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfy-guill\ComfyUI\execution.py", line 189, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\comfy-guill\ComfyUI\execution.py", line 166, in map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfy-guill\ComfyUI\execution.py", line 155, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\comfy-guill\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 318, in load_video
    return load_video_cv(**kwargs)
  File "D:\comfy-guill\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 197, in load_video_cv
    images = torch.from_numpy(np.fromiter(gen, np.dtype((np.float32, (new_size[1], new_size[0], 3)))))
  File "D:\comfy-guill\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 65, in cv_frame_generator
    if total_frames and total_frames.is_integer():
AttributeError: 'int' object has no attribute 'is_integer'
```

Also encountering whilst running guill's new reversed execution version of Comfy, so not sure if related to that or not

**Comment by Darienxccs** [comment]
> Can you post the full error stack from the console?

Just to test it, i create a simple Load Video (Upload) connected to a Video Combine, and got this error windows:

Error occurred when executing VHS_LoadVideo:

'int' object has no attribute 'is_integer'

File "C:\Users\USUARIO\pinokio\api\comfyui.git\app\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\USUARIO\pinokio\api\comfyui.git\app\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\USUARIO\pinokio\api\comfyui.git\app\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\USUARIO\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 269, in load_video
return load_video_cv(**kwargs)
File "C:\Users\USUARIO\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 197, in load_video_cv
images = torch.from_numpy(np.fromiter(gen, np.dtype((np.float32, (new_size[1], new_size[0], 3)))))
File "C:\Users\USUARIO\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 65, in cv_frame_generator
if total_frames and total_frames.is_integer():

**Comment by stephennilor** [comment]
not going to make a PR because it looks like that line hasnt changed in a while but looks like changing line 65 to
`if total_frames and isinstance(total_frames, int):
lets it continue as expected?

**Comment by AustinMroz** [comment]
I had missed that is_integer was added to integers in 3.12. The entire check was pointless as total_frames has already been cast to a float by that point so it has been removed.
