### ISSUE TITLE
Unrecognized option 'x265-params'

### ISSUE THREAD

**Issue by rethink-studios** [Kosinkadink/ComfyUI-VideoHelperSuite#286]
Last week, the Video Combine node worked, and I updated yesterday and received this error?
I tried to fix the node, right-click > Fix node (recreate), but the error persists.

Any ideas?

Unrecognized option 'x265-params'.
Error splitting the argument list: Option not found
[VideoHelperSuite] - WARNING - An error occurred when saving with metadata
!!! Exception during processing !!! An error occurred in the ffmpeg subprocess:
Unrecognized option 'x265-params'.
Error splitting the argument list: Option not found

Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 151, in ffmpeg_process
    proc.stdin.write(frame_data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\COMFYUI_BETA\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 490, in combine_video
    output_process.send(image)
  File "D:\COMFYUI_BETA\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 159, in ffmpeg_process
    raise Exception("An error occurred in the ffmpeg subprocess:\n" \
Exception: An error occurred in the ffmpeg subprocess:
Unrecognized option 'x265-params'.
Error splitting the argument list: Option not found

![image](https://github.com/user-attachments/assets/27831715-4bca-4171-a05c-4dfa44542007)

**Comment by chandujr** [comment]
I have this issue too. Did you find a solution?
```
imageio                    2.37.0
imageio-ffmpeg      0.6.0
```
VHS version: 1.7.7
