### ISSUE TITLE
raise ValueError(f"{video} could not be loaded with cv.")

### ISSUE THREAD

**Issue by fastaipod** [Kosinkadink/ComfyUI-VideoHelperSuite#309]
OS: Ubuntu 22.04.3 LTS
cuda: 12.2

I encountered the following error when loading a video in ComfyUI.
```
Import times for custom nodes:
   0.0 seconds: /workspace/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /workspace/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.0 seconds: /workspace/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /workspace/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.3 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Crystools
   0.3 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-tbox

Setting output directory to: /video/output
Setting input directory to: /video/input
Starting server

To see the GUI go to: http://0.0.0.0:8188
got prompt
[ WARN:0@1799.342] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 165581.395732 ms
[ WARN:0@1799.342] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 165581.644175 ms
[ WARN:0@1799.342] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 165581.661780 ms
[ WARN:0@1799.342] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 165581.672745 ms
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x14b5e400a400] moov atom not found
!!! Exception during processing !!! /video/input/ai_daa98bcd-ef7b-4c15-86ff-8bd5a845fee8.mp4 could not be loaded with cv.
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 271, in load_video
    return load_video_cv(**kwargs)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 143, in load_video_cv
    (width, height, fps, duration, total_frames, target_frame_time) = next(gen)
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 44, in cv_frame_generator
    raise ValueError(f"{video} could not be loaded with cv.")
ValueError: /video/input/ai_daa98bcd-ef7b-4c15-86ff-8bd5a845fee8.mp4 could not be loaded with cv.
```

**Comment by fastaipod** [comment]
I encountered the same issue. Has this problem been resolved?

**Comment by AustinMroz** [comment]
The video isn't compatible with the method used for video loading, so there's not really much that can be fixed.

There's a newish Load Video FFmpeg which might work, but I wouldn't get your hopes up.

**Comment by laurigates** [comment]
Adding a second root cause for this same error, plus a workaround that I think is worth naming in the message itself.

@AustinMroz — you're right that a video OpenCV can't handle isn't fixable *in the cv path*. But in at least one common case the file is fine and VHS can already load it via a different node, and the error doesn't say so.

## The case: AV1-encoded input

`cv2.VideoCapture` **opens** the file but decodes nothing, so the `not video_cap.grab()` branch in `cv_frame_generator` (`videohelpersuite/load_video_nodes.py`) raises. The bundled FFmpeg libs print, to stderr:

```
[av1] Your platform doesn't suppport hardware accelerated AV1 decoding.
[av1] Failed to get pixel format.
```

The reason is that the PyPI `opencv-python` / `opencv-contrib-python` Linux wheels vendor their own FFmpeg build. Listing the bundled shared objects in the wheels' `opencv_*.libs/` directories (4.10.0.84 and 4.11.0.86) shows `libvpx`, but **no** `libdav1d` and no `libaom` — so the only AV1 decoder present is the hwaccel-only one, which then fails.

Controls, all against the same file:

| Reader | Result |
|---|---|
| `cv2` from pip `opencv-contrib-python` 4.10 | `isOpened()=True`, `grab()=False` |
| `cv2` from distro `python3-opencv` 4.5.4 (links system FFmpeg + `libdav1d`) | decodes, returns a valid frame |
| PyAV (vendors FFmpeg 62.x incl. `libdav1d`) | decodes; reports the stream's decoder as `libdav1d` |
| **`VHS_LoadVideoFFmpegPath`** | **decodes** |

The same pip build reads VP9 and H.264 from the same directory without trouble, so this is specific to codecs missing from the vendored FFmpeg rather than a general decode failure.

## Suggested change

The error currently reads:

```python
raise ValueError(f"{video} could not be loaded with cv.")
```

Since VHS already ships **Load Video FFmpeg (Path)** (`VHS_LoadVideoFFmpegPath`) and **Load Video FFmpeg (Upload)** (`VHS_LoadVideoFFmpeg`), which route through `ffmpeg_frame_generator` instead of OpenCV, pointing at them here would turn a dead end into a one-node fix:

```python
raise ValueError(
    f"{video} could not be loaded with cv. If the file uses a codec the "
    "bundled OpenCV FFmpeg lacks (AV1 is the common one), try the "
    "Load Video FFmpeg (Path) / (Upload) nodes, which decode via ffmpeg."
)
```

Happy to open a PR for exactly that one-string change if you'd take it. I have not tested whether the ffmpeg path helps the truncated-file case in the original report, so I'd leave that claim out of the message.
