### ISSUE TITLE
after updating, comes up a error not happen the day before

### ISSUE THREAD

**Issue by jasoncow007** [Kosinkadink/ComfyUI-VideoHelperSuite#338]
![image](https://github.com/user-attachments/assets/2be7b05f-8271-4fdc-86ae-3d09a6f16fef)

!!! Exception during processing !!! 
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 408, in combine_video
    video_format = apply_format_widgets(format_ext, kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 90, in apply_format_widgets
    assert(w[0][0] in kwargs)
           ^^^^^^^^^^^^^^^^^
AssertionError

**Comment by AustinMroz** [comment]
The update included changes to javascript code. You need to refresh the page in order for those changes to actually apply.

**Comment by rishipandey125** [comment]
I am having the same issue

**Comment by zejacky** [comment]
I have the same issue, using the same workflow which worked  2 days ago.

!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 408, in combine_video
    video_format = apply_format_widgets(format_ext, kwargs)
  File "C:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 90, in apply_format_widgets
    assert(w[0][0] in kwargs)
AssertionError

**Comment by zejacky** [comment]
It seems this is a problem with format. I have this error only with video/h264-mp4. Doesn't happen if I choose video/h265-mp4.

**Comment by zejacky** [comment]
> It seems this is a problem with format. I have this error only with video/h264-mp4. Doesn't happen if I choose video/h265-mp4.

After updating the latest Comfyui, it works again.

**Comment by saaldigital-cw** [comment]
Is there still a bug? With  video/h265-mp4 it is fine but i want to use  video/h264-mp4
Even if use the latest Comfyui-Version (v0.3.7) i still get an error

**Comment by longsack** [comment]
Same issue
