### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nodeData')

### ISSUE THREAD

**Issue by AmreshSinha** [Kosinkadink/ComfyUI-VideoHelperSuite#347]
I was trying to open a workflow
specifically this one: https://openart.ai/workflows/discus_disastrous_37/free-digital-human/bcculjSnGEcDuGhoNhkd
on a freshly installed comfyui with manager
and after installing all the missing custom nodes from manager it started to throw this error:

```
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'nodeData')
TypeError: Cannot read properties of undefined (reading 'nodeData')
    at ComfyNode.onConnectionsChange (http://127.0.0.1:8188/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js:450:76)
    at ComfyNode.configure (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:35142:37)
    at ComfyNode.configure (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:121249:15)
    at LGraph2.configure (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:44993:17)
    at LGraph$1.configure (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:120908:26)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:121365:18)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:773:9)
    at async loadWorkflow (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:121021:11)
    at async ComfyApp.setup (http://127.0.0.1:8188/assets/index-DIU5yZe9.js:121026:30)
This may be due to the following script:
/extensions/ComfyUI-VideoHelperSuite/js/VHS.core.js
```

<img width="793" alt="Screenshot 2024-12-26 at 12 32 34 AM" src="https://github.com/user-attachments/assets/4feb4111-60a9-44b5-ab4e-588dcdd222d5" />

I am not sure as to why this is coming up. I was not able to find any existing issue on this as well.
Note: I am a newbie to comfyui.

**Comment by AustinMroz** [comment]
VHS includes code to assist in migrating of older workflows like this one, but it seems there's been changes to ComfyUI itself that break the method I was using to do so. I'll push a quick fix to ensure you don't get an error on load, but some links will need to be manually fixed.

**Comment by AustinMroz** [comment]
VHS added connections for audio input and output in an overly convoluted VHS_AUDIO format for internal use. A number of other custom nodes adopted the format since it was the only option available. Since then ComfyUI introduced a native AUDIO format which is much nicer for actual usage which VHS has swapped to, but it requires adding in "Audio to legacy VHS_AUDIO" and "Legacy VHS_AUDIO to Audio" nodes to maintain compatibility with other nodes that haven't updated.
