### ISSUE TITLE
ffmpeg could not be found

### ISSUE THREAD

**Issue by FUNGnix** [Kosinkadink/ComfyUI-VideoHelperSuite#42]
Hi, the console shows: FETCH DATA from: E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[AnimateDiffEvo] - WARNING - ffmpeg could not be found. Outputs that require it have been disabled.
-
The node panel shows vhs_loadimages & vhs_video combine failed to load.

**Comment by Kosinkadink** [comment]
In the console, there should be a stack trace for the import error. Share that with me here so I can provide further assistance!

**Comment by FUNGnix** [comment]
E:\- SD_v4.4\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-29 20:08:47.057524

Prestartup times for custom nodes:
   0.0 seconds: E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24563 MB, total RAM 65440 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints E:\- SD_v4.4\sd-webui-aki-v4.4\models/Stable-diffusion
Adding extra search path configs E:\- SD_v4.4\sd-webui-aki-v4.4\models/Stable-diffusion
Adding extra search path vae E:\- SD_v4.4\sd-webui-aki-v4.4\models/VAE
Adding extra search path loras E:\- SD_v4.4\sd-webui-aki-v4.4\models/Lora
Adding extra search path loras E:\- SD_v4.4\sd-webui-aki-v4.4\models/LyCORIS
Adding extra search path upscale_models E:\- SD_v4.4\sd-webui-aki-v4.4\models/ESRGAN
Adding extra search path upscale_models E:\- SD_v4.4\sd-webui-aki-v4.4\models/RealESRGAN
Adding extra search path upscale_models E:\- SD_v4.4\sd-webui-aki-v4.4\models/SwinIR
Adding extra search path embeddings E:\- SD_v4.4\sd-webui-aki-v4.4\embeddings
Adding extra search path hypernetworks E:\- SD_v4.4\sd-webui-aki-v4.4\models/hypernetworks
Adding extra search path controlnet E:\- SD_v4.4\sd-webui-aki-v4.4\extensions\sd-webui-controlnet\models
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)
Using pytorch cross attention
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['E:\\- SD_v4.4\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models']
Traceback (most recent call last):
  File "E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 13, in <module>
    from .load_video_nodes import LoadVideoUpload, LoadVideoPath
  File "E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2'

Import times for custom nodes:
   0.0 seconds: E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds (IMPORT FAILED): E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\- SD_v4.4\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[AnimateDiffEvo] - WARNING - ffmpeg could not be found. Outputs that require it have been disabled

**Comment by FUNGnix** [comment]
sorry, i don't know which part is important, so i upload all of it.

**Comment by johnathan2738** [comment]
I think I have the same problem

** ComfyUI start up time: 2023-11-27 23:28:01.377093

Prestartup times for custom nodes:
   0.0 seconds: /Users/johnathan/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /Users/johnathan/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 16384 MB, total RAM 16384 MB
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### Loading: ComfyUI-Manager (V1.5.1)
### ComfyUI Revision: 1737 [39e75862] | Released on '2023-11-26'

[rgthree] Loaded.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json 

[VideoHelperSuite] - INFO - ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
[VideoHelperSuite] - WARNING - ffmpeg could not be found. Outputs that require it have been disabled

Import times for custom nodes:
   0.0 seconds: /Users/johnathan/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.0 seconds: /Users/johnathan/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /Users/johnathan/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   0.2 seconds: /Users/johnathan/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by ThinkdEV9** [comment]
&"python_embeded\python.exe" "python_embeded\get-pip.py" install opencv-python
 and imageio_ffmpeg from powershell
