### ISSUE TITLE
broken pipe when filename prefix has two subdirectories

### ISSUE THREAD

**Issue by nickteeple** [Kosinkadink/ComfyUI-VideoHelperSuite#59]
If I add a second subdirectory to the filename prefix, it crashes when it tries to combine the video. It still writes a single image to the correct directory, but not the mp4 file.  Using a very simple VAE Decode (Tiled) to Video Combine workflow. 

```
ERROR:root:Failed to validate prompt for output 101:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: images
ERROR:root:* VHS_VideoCombine 101:
ERROR:root:  - Required input is missing: images
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 126:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: images
ERROR:root:* Image Save 126:
ERROR:root:  - Required input is missing: images
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 135:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: images
ERROR:root:* VHS_VideoCombine 135:
ERROR:root:  - Required input is missing: images
ERROR:root:Output will be ignored
H:\Documents\stable-diffusion\comfy\ComfyUI_windows_portable_nvidia_cu118_or_cpu_v1\ComfyUI_windows_portable\ComfyUI\output\subdirectory01\subdirectory02\really-long-filename.mp4: No such file or directory
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Documents\stable-diffusion\comfy\ComfyUI_windows_portable_nvidia_cu118_or_cpu_v1-new-shit\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Documents\stable-diffusion\comfy\ComfyUI_windows_portable_nvidia_cu118_or_cpu_v1-new-shit\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Documents\stable-diffusion\comfy\ComfyUI_windows_portable_nvidia_cu118_or_cpu_v1-new-shit\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Documents\stable-diffusion\comfy\ComfyUI_windows_portable_nvidia_cu118_or_cpu_v1-new-shit\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 215, in combine_video
    proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

Prompt executed in 0.32 seconds
```

**Comment by AustinMroz** [comment]
I wasn't able to reproduce the issue on linux or windows.

The broken pipe error message (which I'll make a note to change the description of) just indicates that the ffmpeg process ran into an error and closed before it could process all the input. Could you check the console to see if it provides information on why the ffmpeg process failed?

**Comment by nickteeple** [comment]
I will close it for now. It's something else that's wrong, but I don't know how to dig into it further. Nothing else in the console. If I open an older version of my workflow, then I don't see the same issue.
