### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by NOeSIS-yu** [Kosinkadink/ComfyUI-VideoHelperSuite#62]
<img width="867" alt="屏幕截图 2023-11-16 000958" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/116642879/4bb44326-5ec0-492f-bce3-ce5f06214849">
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 14, in <module>
    from .load_video_nodes import LoadVideoUpload, LoadVideoPath
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import E:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2'
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

**Comment by ThinkdEV9** [comment]
&"python_embeded\python.exe" "python_embeded\get-pip.py" install opencv-python
and imageio_ffmpeg from powershell

**Comment by Xorba001** [comment]
I ran into the same problem and got it fixed.
I was seeing numba in WASNode and got to try to resolve this. I found in the WASNode an install.bat file for their module.

What it did, ran the thing, it installed python_embedded stuff.

I restarted the ComfyUI, and the CV2 error was gone !

Had previously installed opencv, ffmpeg, imageio_ffmpeg to no avail. 
after running the install for WAS, VHS_ error red warning was gone and workspace loads just fine.

Hope this helps... somehow !
It's a work around but looking at the WASNode way that it embedded python might shed a light on the issue.
