### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe error

### ISSUE THREAD

**Issue by ibadmore** [Kosinkadink/ComfyUI-VideoHelperSuite#63]
2023-11-16T05:00:03.543844963Z /opt/micromamba/envs/comfyui/bin/ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory

2023-11-16T05:00:03.543856373Z ERROR:root:!!! Exception during processing !!!
2023-11-16T05:00:03.543858364Z ERROR:root:Traceback (most recent call last):
2023-11-16T05:00:03.543859594Z   File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
2023-11-16T05:00:03.543861524Z     output_data, output_ui = get_output_data(obj, input_data_all)
2023-11-16T05:00:03.543862874Z   File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
2023-11-16T05:00:03.543864114Z     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2023-11-16T05:00:03.543865914Z   File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
2023-11-16T05:00:03.543867054Z     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2023-11-16T05:00:03.543868214Z   File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 216, in combine_video
2023-11-16T05:00:03.543870004Z     proc.stdin.write(frame.tobytes())
2023-11-16T05:00:03.543871094Z BrokenPipeError: [Errno 32] Broken pipe
2023-11-16T05:00:03.543872194Z 
2023-11-16T05:00:03.543873374Z Prompt executed in 1175.84 seconds

**Comment by AustinMroz** [comment]
That's bizarre. The broken pipe error message is simply an error message that the ffmpeg subprocess, but the provided log has the important information
```
2023-11-16T05:00:03.543844963Z /opt/micromamba/envs/comfyui/bin/ffmpeg: error while loading shared libraries: libopenh264.so.5: cannot open shared object file: No such file or directory
```
It's unusual that ffmpeg would complain about a missing h264 library when you are trying to save as a webm which usually uses vp9 as a codec.

I would first check if trying to save with the video/h264-mp4 format produces the same error message.

If so, I would ask you edit the video_formats/webm.json to
```json
{
    "main_pass":
    [
        "-n",
        "-pix_fmt", "yuv420p",
        "-c:v", "libvpx-vp9"
    ],
     "extension": "webm"
}
```
I had thought not forcing a codec, would ensure ffmpeg picks an available codec, but it's possible it'll fix your issue if ffmpeg is forced to use the more common vp9 codec.
