### ISSUE TITLE
out of memory with load video

### ISSUE THREAD

**Issue by Pimax1** [Kosinkadink/ComfyUI-VideoHelperSuite#67]
Hi there,

I am trying to load a video and save every 4 frames. workflow is very simple, just the video loader and save image. 
![image](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/48963533/67f2b47d-f650-44de-9a2a-5c4f1b1e5d02)

the video is 3 min long and 60 fps but video loader is super slow and will get out of memory quickly :

Traceback (most recent call last):
  File "E:\dev\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\dev\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\dev\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\dev\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 174, in load_video
    raise RuntimeError(f"Failed to load video: {kwargs['video']}\ndue to: {e.__str__()}")
RuntimeError: Failed to load video: E:\dev\ComfyUI\output\wildfire\wildfire.mp4
due to: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 68951347200 bytes.

I have 64gb RAM, its all used up to load this 3 min video and anyway the tool cant load it.

 I am not sure if its normal/expected to have  so much RAM consumed.

instead I use ffmpeg directly, can deal with this video super quickly and no ram consumption. But still I would rather be able to make use of this tool in comfyui

**Comment by Pimax1** [comment]
well i get the same thing with load images, 2809 images to load, they are 804 mb total. my ram just rising rising rising to reach 64gb and the tool fails to load the images: 

  File "E:\dev\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\dev\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\dev\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\dev\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_images_nodes.py", line 136, in load_images
    return load_images(directory, **kwargs)
  File "E:\dev\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_images_nodes.py", line 74, in load_images
    return (torch.cat(images, dim=0), torch.stack(masks, dim=0), image_count)
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 69896908800 bytes.

**Comment by AustinMroz** [comment]
It's not normal to see ram usage this high, but it's not a surprise given the length and frame rate of the video you're using.

The data format for images in comfy ui is a 32 bit float for each channel (R,G,B) of each pixel of the image, all uncompressed. I would put a rough estimate of the ram required to load a set of images at around 16x the size of the images on disk. I'll take a look at things since you're seeing usage about 4x higher than my rough estimation, but it seems like you've got a fairly non-standard workflow.

Normally I'd give a slew of recommendations to drastically reduce the quality to what would be appropriate for actually doing processing on the video within the workflow:
- Set `force_rate` to 8. That'll cut the required ram by about 1/8th
- Use `force_size` to lower the image resolution. The newer AnimateDiff models were trained on 512x512. I believe the current implementation doesn't resize until after all frames are loaded, so it may not reduce the ram usage of initial load, but should probably reduce the required ram by another 1/16th after the initial load
- Use `frame_load_cap` along with `skip_first_frames` to process the video in batches.

But it sounds like you're just wanting to use the plugin as a convenience tool and there won't be much optimization I can do given the need for comfy ui to keep all images loaded at once, uncompressed in ram compared to using raw ffmpeg which can stream through the file, saving the output to disk as it goes.

**Comment by Pimax1** [comment]
thanks, I reduced my video size from 1920x1080 to 768x432. now its using 10GB RAM to load vs 145 mb from disk.
I am trying to generate a long animatediff animation in the end. I am not sure yet if its easy to implement any length animateDiff animation but will try.   I noticed that AnimateDiff cli repo can do any lenght so there should be a way.
thanks a lot for your answer.

**Comment by AustinMroz** [comment]
To my knowledge, AnimateDiff-Evolved closely adheres to the sliding window code of AnimateDiff cli and cli should have the same limitation of needing the whole video in ram to do each denoise step simultaneously.

I'll check the source code for AnimateDiff cli when I have time, but I would expect it to have roughly the same ram requirements.

**Comment by jamesmgg** [comment]
hey y'all, just wanted to chime in that I'm running into this issue as well... so far I've only noticed it to be a problem with AnimateDiff... but I haven't tried to use VHS for anything else.

The weird problem is that other people running the same exact workflow with the same exact video don't see the same VRAM issue. When other people ran my workflow it used up 10GB of VRAM, but for me it goes above 24GB and goes into share GPU memory.

**Comment by jamesmgg** [comment]
for anyone running into this problem with animatediff evolved... make sure to set `apply_v2_models_properly=True` 

that fixed the VRAM issue for me

**Comment by Kosinkadink** [comment]
To note, this is an issue with your pytorch somehow, and not an AnimateDiff-Evolved issue. Setting it to true and using a v2 based models means the required groupnorm hack off v1 based models will not be used, so something about your current pytorch setup is unhappy about the groupnorm hack required by v1 based models, including AnimateDiff-SDXL and HotshotXL.

Does give a good place to look to debug the particular issue you're experiencing.
