### ISSUE TITLE
Can't Save/Render Video Formats - [Errno 32] Broken pipe - Unrecognized option 'crf'

### ISSUE THREAD

**Issue by Kinglord** [Kosinkadink/ComfyUI-VideoHelperSuite#69]
Hi there,

Just got this node today and maybe this is something stupid I've messed up but whenever I try to use a non-image save type (any video ones) this error pops up and stops the process.

```
2023-11-18 00:21:20 Unrecognized option 'crf'.
2023-11-18 00:21:20 Error splitting the argument list: Option not found
2023-11-18 00:21:20 ERROR:root:!!! Exception during processing !!!
2023-11-18 00:21:20 ERROR:root:Traceback (most recent call last):
2023-11-18 00:21:20   File "/workspace/ComfyUI/execution.py", line 153, in recursive_execute
2023-11-18 00:21:20     output_data, output_ui = get_output_data(obj, input_data_all)
2023-11-18 00:21:20   File "/workspace/ComfyUI/execution.py", line 83, in get_output_data
2023-11-18 00:21:20     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2023-11-18 00:21:20   File "/workspace/ComfyUI/execution.py", line 76, in map_node_over_list
2023-11-18 00:21:20     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2023-11-18 00:21:20   File "/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 199, in combine_video
2023-11-18 00:21:20     proc.stdin.write(frame.tobytes())
2023-11-18 00:21:20 BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by unphased** [comment]
I have the same problem. I'm running it in docker and saw some helpful logs adjacent to it, which led me to look at: 

```
root@61e62592e597:/stable-diffusion# /opt/conda/bin/ffmpeg -version
ffmpeg version 4.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
configuration: --prefix=/opt/conda/conda-bld/ffmpeg_1597178665428/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh --cc=/opt/conda/conda-bld/ffmpeg_1597178665428/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-pic --enable-pthreads --enable-shared --disable-static --enable-version3 --enable-zlib --enable-libmp3lame
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
```
clearly this is ffmpeg not having been built with libx264, which makes the command call fail. It was shown to me as `subprocess.CalledProcessError: Command '['/opt/conda/bin/ffmpeg', '-v', 'error', '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-s', '1432x800', '-r', '24', '-i', '-', '-crf', '20', '-n', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '/stable-diffusion/output/Final_00001.mp4']' returned non-zero exit status 1.`

So it would appear that if we use a non-garbage ffmpeg, this will not be a problem. How you approach that is up to you, it seems like on my end I could fix it with a simple ffmpeg install in the dockerfile but it may not be this simple for you.

**Comment by unphased** [comment]
I can confirm that i rebuilt after having included `apt install ffmpeg`, i still got the problem, then i went ahead and 

    root@e37df084e7a1:/stable-diffusion# rm /opt/conda/bin/ffmpeg
    root@e37df084e7a1:/stable-diffusion# ln -s /bin/ffmpeg /opt/conda/bin/ffmpeg

(lmao) 

And it worked.

**Comment by unphased** [comment]
You may be able to avoid the issue by simply choosing a different output format. the ffmpeg provided by whatever is providing it wasn't compiled with x264...

**Comment by chadly** [comment]
thanks @unphased. clever way to switch it to use the system `ffmpeg`

added this to my dockerfile: `RUN rm /opt/conda/bin/ffmpeg && ln -s /bin/ffmpeg /opt/conda/bin/ffmpeg`

[works perfectly now](https://github.com/chadly/comfy_ui/blob/92cc9721a1587064d65ca551c107a2ed4f3cdf1a/Dockerfile#L57)

now to figure out how to actually use svd...
![rocket](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/1761510/1ed8a14d-8775-4083-b27d-ac3438bf01fc)

**Comment by unphased** [comment]
It's very exciting and now we eagerly await for controlnet/keyframe type features for this thing.
