### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by MY20212021** [Kosinkadink/ComfyUI-VideoHelperSuite#72]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 199, in combine_video
    proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

always error，had change V9

**Comment by Lalimec** [comment]
Same issue

```
/home/ubuntu/ComfyUI/temp/metadata.txt: Invalid data found when processing input
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ubuntu/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 199, in combine_video
    proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

Prompt executed in 60.07 seconds
```

**Comment by Mindspherical** [comment]
Error 32 as well, tried rolling back versions, same issue. Could it be a conflict with the newest ComfyUI?

<img width="735" alt="image" src="https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/117719106/44ec02b3-8292-4adc-8563-c055f2a2a873">

**Comment by Kosinkadink** [comment]
Can you check if you get the error if you toggle "save_metadata" to off in the node?

**Comment by alexbofa** [comment]
> Can you check if you get the error if you toggle "save_metadata" to off in the node?

Yes, it's work when `save_metadata = false`

**Comment by Lalimec** [comment]
Yes, that solves the problem.

**Comment by Kosinkadink** [comment]
Alrighty, a PR has been merged that should not cause metadata to prevent you from saving the video - if you can, could you pull latest, turn on metadata saving, and see if, besides an error logged in console saying there was an issue saving with metadata, the video gets saved anyway?

**Comment by alexbofa** [comment]
Yes, it's work for me! Thanks!

**Comment by Kosinkadink** [comment]
Assuming the cause for the OP's issue was the same as the other replies on this post, since this is fixed, I will close the issue. If this ended up not solving your issue @MY20212021, feel free to reopen the issue and post the full error stack from the console.

**Comment by Rizwanali324** [comment]
> > Can you check if you get the error if you toggle "save_metadata" to off in the node?
> 
> Yes, it's work when `save_metadata = false`

where did you add this
